# Start AeroSpace at login
start-at-login = true

# after-startup-command = [
#   'exec-and-forget /bin/zsh -lc "/usr/local/bin/sketchybar --reload"'
# ]
#

# exec-on-workspace-change = [
# 	'/bin/zsh', '-c',
#     '/opt/homebrew/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
# ]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 20

default-root-container-layout = 'accordion'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
outer.top = [{ monitor.main = 0 },  0]

[mode.main.binding]
cmd-slash = 'layout tiles horizontal vertical'
cmd-comma = 'layout accordion horizontal vertical'

# cmd-f = 'fullscreen'
f11 = 'macos-native-fullscreen'


# See: https://nikitabobko.github.io/AeroSpace/commands#resize
cmd-shift-minus = 'resize smart -50'
cmd-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
cmd-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
cmd-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
cmd-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
cmd-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
cmd-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
cmd-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
cmd-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
cmd-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
cmd-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'

cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

# cmd-shift-h = 'join-with left'
# cmd-shift-j = 'join-with down'
# cmd-shift-k = 'join-with up'
# cmd-shift-l = 'join-with right'


# These are invoked from karabiner-elements. Which disables the default macOS behavior of cmd-tab and cmd-shift-tab.
# cmd-tab = 'workspace-back-and-forth'
# cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'
