# https://docs.rs/i3status-rs/latest/i3status_rs/
icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "material-nf"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %m-%d %R %Z', l:en_US) "
short = " $icon $timestamp.datetime(f:%R) "
[[block.click]]
button = "right"
cmd = "xdg-open https://calendar.google.com"
[[block.click]]
button = "left"
cmd = "gnome-clocks"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "custom"
command = "current-refresh-rate"
[[block.click]]
button = "left"
cmd = "toggle-refresh-rate;i3 restart" # There might be a better way to update, only i3status-rs
[[block.click]]
button = "right"
cmd = "toggle-auto-rotate"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol -t 3"

[[block]]
block = "sound"
device_kind = "source"
[[block.click]]
button = "left"
cmd = "pavucontrol -t 4"
